### ISSUE TITLE
Remove POM

### ISSUE THREAD

**Issue by superiorpancakes** [datasets/s-and-p-500-companies#12]
now a private holding co

POM	Pepco Holdings Inc.	Utilities	26.52	4.07	20.64	1.28	17.35	21.61

**Comment by rgrp** [comment]
@lexman could you run your regular update here? (And maybe we can start automating that!)

**Comment by lexman** [comment]
Hello,

sorry for the delay... The data have been updated.

About automating, I've started a [tutorial](https://github.com/lexman/ex-continuous-processing) to explain how to acheive it. Don't expect it to be ready before a  couple of weeks, because my connection is very poor where I am at the moment...

**Comment by lexman** [comment]
Opened an [issue](https://github.com/datasets/s-and-p-500-companies/issues/14) for automatic update
