### ISSUE TITLE
Not pulling latest info from wikipedia

### ISSUE THREAD

**Issue by jmcgrath207** [datasets/s-and-p-500-companies#17]
Hey guys,

There seems to be a issue with removing and adding S&P 500 holdings. For example I still see EMC in the S&P 500 according to the JSON API I used.

http://data.okfn.org/data/core/s-and-p-500-companies/r/constituents-financials.json

Thank you,

John

**Comment by rufuspollock** [comment]
Thaks for reporting and this is now fixed in https://github.com/datasets/s-and-p-500-companies/commit/5dfdfbc3b9f52802f89e72da6e050b5cafdec4a6 - our daily pipeline broke for some reason but now this is back up.

Note the authoritative location is https://datahub.io/core/s-and-p-500-companies - and this includes JSON versions etc.
