### ISSUE TITLE
Date of data

### ISSUE THREAD

**Issue by antares2001** [datasets/s-and-p-500-companies#22]
Hello!

This is a great tool! Is it somehow possible to acquire the issuance data of the facts that are provided in the data csv? Since it's a bit losing value if I don't know when the information was filed.

Thanks!

**Comment by rufuspollock** [comment]
Thaks for reporting and this is now fixed in https://github.com/datasets/s-and-p-500-companies/commit/5dfdfbc3b9f52802f89e72da6e050b5cafdec4a6 - our daily pipeline broke for some reason but now this is back up and will be kept updated.

Note the authoritative location is https://datahub.io/core/s-and-p-500-companies - and this includes JSON versions etc.
